# Generated by Django 3.0.5 on 2025-05-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dur', models.PositiveIntegerField()),
                ('cred', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='app5.Course'),
        ),
    ]
